---
# =============================================================================
# EXERCICE 2 : Rôle OpenSearch - Variables
# =============================================================================

opensearch_version: "2.11.1"
opensearch_home: "/usr/share/opensearch"
opensearch_data_dir: "/var/lib/opensearch"
opensearch_logs_dir: "/var/log/opensearch"
opensearch_cluster_name: "p5-opensearch-cluster"
opensearch_node_name: "p5-opensearch-node-1"
opensearch_network_host: "0.0.0.0"
opensearch_discovery_type: "single-node"
