---
# =============================================================================
# EXERCICE 2 : Rôle Filebeat - Variables
# =============================================================================

filebeat_version: "8.11.1"
logstash_host: "localhost"
logstash_port: 5044
