version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3

  - package-ecosystem: npm
    directory: /application/angular
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    groups:
      angular-minor-patch:
        applies-to: version-updates
        patterns:
          - "@angular*"
          - "angular-eslint"
          - "@angular-eslint/*"
          - "zone.js"
        update-types:
          - minor
          - patch
      angular-tooling-minor-patch:
        applies-to: version-updates
        patterns:
          - "eslint"
          - "typescript-eslint"
          - "typescript"
          - "jsdom"
          - "vitest"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "@angular*"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "angular-eslint"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@angular-eslint/*"
        update-types:
          - "version-update:semver-major"
      - dependency-name: typescript
        update-types:
          - "version-update:semver-major"
      - dependency-name: eslint
        update-types:
          - "version-update:semver-major"
      - dependency-name: jsdom
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: terraform
    directory: /terraform/exercice-1
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: hashicorp/aws
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: terraform
    directory: /terraform/exercice-2
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: hashicorp/aws
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: terraform
    directory: /terraform/exercice-3
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: hashicorp/aws
        update-types:
          - "version-update:semver-major"
