version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /application/angular
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
 
  - package-ecosystem: terraform
    directory: /terraform/exercice-1
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3

  - package-ecosystem: terraform
    directory: /terraform/exercice-2
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3

  - package-ecosystem: terraform
    directory: /terraform/exercice-3
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3
