---
# =============================================================================
# EXERCICE 2 : Rôle Logstash - Variables
# =============================================================================

logstash_version: "8.11.1"
logstash_listen_port: 5044
