blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/mathiasseguincadiche/p5_Openclassrooms/tree/main/docs
    about: Consultez la documentation complète du projet.
  - name: 💬 Discussions
    url: https://github.com/mathiasseguincadiche/p5_Openclassrooms/discussions
    about: Posez des questions ou discutez avec la communauté.
