---
# =============================================================================
# EXERCICE 3 : Rôle HAProxy - Handlers
# =============================================================================

- name: restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
  
  listen: "restart haproxy"
